### PR TITLE
refactor!: types

### PR DESCRIPTION
**Pull request by zAlweNy26**
I tried my best to fix the types so that we don't get anymore the error of issue #12 . Tell me what do you think!

PS: I may have over-typed a bit, I hope that's not a problem :)

### CODE REVIEW

**Comment by Barbapapazes** [comment]
> I tried my best to fix the types so that we don't get anymore the error of issue #12 . Tell me what do you think!
> 
> PS: I may have over-typed a bit, I hope that's not a problem :)

Hey 👋,

Thank you so much for this.

Have you succeed in typecheck the playground?

I try but it's like vue-tsc was not aware of `tsconfig.json` in the server folder.

<details>
<summary>vue-tsc log</summary>

```sh
nuxt-authorization/playground on  correct-types [!] via ⬢ v20.17.0 
➜ nr typecheck                  

> nuxt-authorization-playground@ typecheck /Users/esoub/dev/p/nuxt-authorization/playground
> nuxi typecheck

server/api/products/[id].patch.ts:11:19 - error TS2345: Argument of type 'H3Event<EventHandlerRequest>' is not assignable to parameter of type 'BouncerAbility<any>'.
  Type 'H3Event<EventHandlerRequest>' is missing the following properties from type 'BouncerAbility<any>': original, execute, allowGuest

11   await authorize(event, editProduct, product)
                     ~~~~~

server/api/products/index.get.ts:4:19 - error TS2345: Argument of type 'H3Event<EventHandlerRequest>' is not assignable to parameter of type 'BouncerAbility<any>'.

4   await authorize(event, listProducts)
                    ~~~~~

server/api/products/index.post.ts:4:19 - error TS2345: Argument of type 'H3Event<EventHandlerRequest>' is not assignable to parameter of type 'BouncerAbility<any>'.

4   await authorize(event, createProduct)
                    ~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  server/api/products/[id].patch.ts:11
     1  server/api/products/index.get.ts:4
     1  server/api/products/index.post.ts:4

[1:39:53 PM]  ERROR  Command failed with exit code 2: '/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/vue-tsc@2.1.6_typescript@5.5.4/node_modules/vue-tsc/bin/vue-tsc.js' --noEmit

  at getFinalError (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index3.mjs:1124:9)
  at makeError (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index3.mjs:3604:16)
  at getAsyncResult (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index3.mjs:7831:4)
  at handlePromise (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/chunks/index3.mjs:7814:17)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/chunks/typecheck.mjs:81:7)
  at async runCommand$1 (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1648:16)
  at async runCommand$1 (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/nuxi@3.14.0/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7) 



[1:39:53 PM]  ERROR  Command failed with exit code 2: '/Users/esoub/dev/p/nuxt-authorization/node_modules/.pnpm/vue-tsc@2.1.6_typescript@5.5.4/node_modules/vue-tsc/bin/vue-tsc.js' --noEmit

 ELIFECYCLE  Command failed with exit code 1.
```

</details>

**Comment by zAlweNy26** [comment]
Yeah I thought that error was a mistake of my local setup, hoping that it was OK for the CI since the build was working fine.
It seems it sees the `authorize` method defined for the client and not the one for the server.

**Comment by Barbapapazes** [comment]
> Yeah I thought that error was a mistake of my local setup, hoping that it was OK for the CI since the build was working fine. It seems that it sees the `authorize` method defined for the client and not the one for the server, so complaining about the types.

Yes exactly but I think it's more related to `vue-tsc` than to this module.

**Comment by zAlweNy26** [comment]
It seems ok now...?

**Comment by Barbapapazes** [comment]
> It seems ok now...?

Yes! Thank you for this 💜 and I've opened an issue on the Nuxt repo about this `vue-tsc` issue.

**Pull request merged**
